apiVersion: v1
entries:
  alibaba-rsocket-broker:
  - apiVersion: v2
    appVersion: 1.1.1
    created: "2021-06-10T17:07:44.71425-07:00"
    description: A Helm chart for Alibaba RSocket Broker
    digest: 22a5a73dfe2b769bbcf7a1b13f23f291426ba6dd73d3706ec250951f3aa47852
    home: https://github.com/alibaba/alibaba-rsocket-broker
    icon: https://rsocket.io/img/r-socket-pink.svg
    keywords:
    - rsocket
    - broker
    - reactive
    maintainers:
    - email: libing.chen@gmail.com
      name: linux_china
      url: https://github.com/linux_china
    name: alibaba-rsocket-broker
    sources:
    - https://github.com/alibaba/alibaba-rsocket-broker
    - https://github.com/alibaba-rsocket-broker/rsocket-broker-helm
    type: application
    urls:
    - https://github.com/alibaba-rsocket-broker/rsocket-broker-helm/releases/download/0.1.1/alibaba-rsocket-broker-0.1.1.tgz
    version: 0.1.1
generated: "2021-06-10T17:07:44.713628-07:00"
